name: Build and Test Junction

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kernel headers and build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-headers-$(uname -r) build-essential
          sudo apt-get install -y flex bison libelf-dev libssl-dev

      - name: Run install.sh
        run: scripts/install.sh

      - name: Install rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=nightly

      - name: Compile Junction
        run: scripts/build.sh
